# Generated by Django 3.0.5 on 2023-11-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20231124_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
